---
title: "Distrital"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r library}
library(tidyverse)
library(sf)

info_distrital <- readxl::read_xlsx("data/Diresas/informacion_distritos.xlsx") %>% 
  filter(Fecha == as.Date("2020-04-26"))

mapa_distrital <- read_sf("data/distrital_shp/Distritos.shp")%>%
  select(Region = NOMBDEP,
         Provincia = NOMBPROV,
         Distrito = NOMBDIST,
         geometry)
```

```{r eda}
regiones <- info_distrital %>% 
  filter(!is.na(Valor)) %>% 
  distinct(Region) %>% 
  pull(Region)

plot_region <- function(data, region){
  data %>% 
  left_join(info_distrital) %>% 
  filter(Region %in% region) %>% 
  ggplot()+
  geom_sf(aes(fill = Valor)) +
  scale_x_discrete()+
  labs(title = paste("Contagios por distrito en", region))+
  theme(legend.position = "none")
}

plot_region(mapa_distrital, "AMAZONAS")

# Ejemplo de uso
map(c("AMAZONAS", "APURIMAC"), ~plot_region(mapa_distrital, .x)) %>% 
  walk(print)

```




